version: 2
jobs:
  build:
    # only build the circleci branch for now
    branches:
      only:
        - master
    docker:
      # specify the version
      - image: circleci/golang:1.13.4
    working_directory: /go/src/terratest/
    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
      - run: curl -L -s https://releases.hashicorp.com/packer/1.2.3/packer_1.2.3_linux_amd64.zip -o /go/bin/packer.zip && unzip /go/bin/packer.zip -d /go/bin && chmod +x /go/bin/packer
      - run: curl -L -s https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip -o /go/bin/terraform.zip && unzip /go/bin/terraform.zip -d /go/bin && chmod +x /go/bin/terraform
      - run: cd test
      - run: go mod init terraform_aws_example_test
      - run: go mod tidy
      #- run: go get k8s.io/client-go@master
      - run: go test -v -timeout 90m .
