version: 2.1
orbs:
  slack: circleci/slack@3.3.0
executors:
  my-executor:
    docker:
      - image: circleci/golang:1.13.4

jobs:
  start-workflow:
    executor: my-executor
    steps:
      - run: |
          name: Workflow Start job
          command: |
            echo "Workflow Start!"
            echo ${CIRCLE_BUILD_URL}
            echo ${CIRCLE_COMPARE_URL}
            echo ${CIRCLE_JOB}
  test-iac:
    executor: my-executor
    working_directory: /go/src/terratest/
    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
      - run: curl -L -s https://releases.hashicorp.com/packer/1.2.3/packer_1.2.3_linux_amd64.zip -o /go/bin/packer.zip && unzip /go/bin/packer.zip -d /go/bin && chmod +x /go/bin/packer
      - run: curl -L -s https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip -o /go/bin/terraform.zip && unzip /go/bin/terraform.zip -d /go/bin && chmod +x /go/bin/terraform
      - run: cd test; dep init
      #- run: go get k8s.io/client-go@master
      - run: cd test; go test -v -run TestTerraformAwsNetworkExample

workflows:
  iac-pipeline:
    jobs:
      - start-workflow:
          name: start-workflow
      - test-iac:
          name: test-iac-code
          requires:
            - start-workflow

